FE = float(input("put your Foundation English score"))
GB = float(input("put your General Business score"))
ICS = float(input("put your Introduction to Computer Systems score"))
C_program =  float(input("put your Computer Programming score"))

print ("--- Your Score ---")
print ("Foundation English" , FE)
print ("General Business" , GB )
print ("Introduction to Computer Systems" , ICS)
print ("Computer Programming" , C_program)